---
# Organization to pull metrics from
organization: 'tv2'

# Start date to pull metrics from
since: '2024-09-01'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/dvt-repos-dashboard'
